install.packages("bird.sta.csv")
require("bird.sta.csv")
read.csv(here("data", "bird.sta.csv"))
dat_bird <- data.frame(read.csv(here("data", "bird.sta.csv")))
require(here)
hist(main= "Histogram of HAWO", x="HAWO")
read.csv(here("birds_metadata.pdf"))
read.csv(here("data", "hab.sta.csv"))
dat_habitat <- data.frame(read.csv(here("data", "hab.sta.csv")))
name(dat_habitat)
hist(dat_bird$CBCH)
pairs(dat_bird[, c("BHGR", "CBCH", "OCWA")])
