install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
class(penguins)
penguins = data.frame(penguins)
mean(penguins$body_mass_g)
head(penguins)
summary(penguins)
plot(x= penguins$bill_length_mm, y= penguins$flipper_length_mm)
